### PR TITLE
run.sh was not using the local catalogDir. Would be a problem when flocking

### PR DESCRIPTION
**Pull request by yiiyama**
Essentially, passing ./catalog instead of $catalogDir to the macros.

### CODE REVIEW

**Comment by cpausmit** [comment]
I do not think there is  an error. The 'fixes' do not look right to me. Did you test whether the condor and the interactive version still do what they are supposed to do? All is working right now, so I prefer not to screw that up.

**Comment by yiiyama** [comment]
The change in process.sh could be something unnecessary. Not sure since I never used the file that is being written in the line in question. It is related to submission to CRAB I suppose.
On the other hand the other change is in submit.sh and therefore does not affect the interactive version of job running. Currently what happens is the following:
 - process.sh: passes $MIT_CATALOG, which evaluates to /home/cmsprod/catalog to submit.sh as the second argument
 - submit.sh: sets the second argument of condor jobs (passed to run.sh) to $catalogDir, which is its second argument (i.e. $MIT_CATALOG)
 - run.sh: calls the macro function with $catalogDir as the catalog location, where $catalogDir is the second argument of the script.
So the macro does not use the catalog directory that has been packed up and shipped with it to the condor working directory, but rather reads directly from T3 /home.
I can be missing something though - could you check one of the .out files from the skim jobs and see what arguments are being passed to the macro function?

**Comment by cpausmit** [comment]
hey man are you online?

**Comment by yiiyama** [comment]
Hi Christoph,

I am online @EWR now, but might lose connection in ~10 minutes.

Yutaro
---------------------------------------------------------------

CERN Bat. 32 4-A20
Massachusetts Institute of Technology
yutaro.iiyama@cern.ch

**Comment by cpausmit** [comment]
have a good flight.
Let's get skimming going once you are back at CERN.
High Priority.

Christoph

**Pull request merged**
